---
- name: Clone | stop standby postgres
  service:
    name: "{{ postgres_service }}"
    state: stopped
  when:
    - not repmgr_is_master|bool
    - result is failed

- name: Clone | clone standby nodes
  command: "{{ repmgr_bin_dir }}/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} -h {{ repmgr_default_master }} \
            -U {{ repmgr_user }} -d {{ repmgr_dbname }} standby clone -F"
  when:
    - not repmgr_is_master|bool
    - result is failed
  become: true
  become_user: "{{ repmgr_postgres_admin_user }}"

- name: Clone | start standby postgres
  service:
    name: "{{ postgres_service }}"
    state: started
  when:
    - not repmgr_is_master|bool
    - result is failed
