---
- name: Register standby | register standby node
  command: "{{ repmgr_bin_dir }}/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} standby register"
  when:
    - not repmgr_is_master|bool
    - result is failed
  become: true
  become_user: "{{ repmgr_postgres_admin_user }}"
  notify: start repmgrd
