---
- name: Register master | register master node
  command: "{{ repmgr_bin_dir }}/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} primary register"
  become: true
  become_user: "{{ repmgr_postgres_admin_user }}"
  when:
    - repmgr_is_master|bool
    - result is failed
  notify: start repmgrd

- name: Register master | ensure repmgrd is started
  service:
    name: "{{ repmgr_service }}"
    state: started
