---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: anxs.postgresql
      vars:
        postgresql_version: 12
        ansible_python_interpreter: "{{ 'python3' if ansible_distribution == 'Debian' else 'python' }}"
    - role: flipp3r90.repmgr
